<?php

namespace wrdickson\apibook;

//  dev on localhost
define('DB_HOST', 'localhost');
define('DB_USER', 'mto_admin');
define('DB_PASS', 'quetzal123');
define('DB_NAME', 't_book_db');
define('SERVER_NAME', 'localhost');
define('DEFAULT_LOCALE', 'en');
define('DEFAULT_TIMEZONE', 'America/Denver');
define('CURRENCY_CODE', 'USD');
define('CURRENCY_FRACTION_DIGITS', '2');
define('CURRENCY_NUMERIC_CODE', '840');
define('CURRENCY_NAME', 'US Dollar');
define('JWT_KEY', 'wx9BviAiHrv52l3UnxqfrSdZFgBlWeN4d8qJFfb7biDYsK2hshuAB8kuT62UB0');

//  production config.php is generated by install script
